@startuml
title Consensus protocols for replicated state machines

package "BFT School" {
object "Paxos" as paxos
object "Raft" as raft
object "Rampart" as rampart
object "SecureRing" as securering
object "DLS" as dls
object "PBFT" as pbft
object "HoneyBadgerBFT" as hbbft
}

package "Cryptoeconomis" {
object "Generic PoS" as pos
object "Casper CBC" as cbc
object "Ouroboros" as ouroboros
object "PoW" as pow
object "Casper FFG" as ffg
pow --> ffg
}

package "Hybrids" {
object "Tendermint" as tendermint
object "Polkadot" as polkadot
}

pos --> cbc
pos --> ouroboros
pos --> tendermint
pos --> ffg

rampart --> pbft
securering --> pbft
pbft --> hbbft
dls --> tendermint
hbbft --> polkadot
tendermint --> polkadot
pbft --> ffg

object dls {
  set of partially synchronous algos
  ⅓ byzantine tolerance
}

object tendermint {
  partially synchronous
  ⅓ byzantine tolerance
}

object polkadot {
  (no complete consensus description)
  Validators sign blocks in Replay chain
  - selected by Nominated Proof of Stake (NPoS)
  - incentivised by (1) inflation (2) transaction fees
  - sr-NaS: prevented by long stake withholding
  - lr-NaS: prevented by hardcoding block hash snapshots in clients code
}
@enduml
