@startuml
object "Rampart" as rampart
object "SecureRing" as securering
object "DLS" as dls
object "PBFT" as pbft
object "HoneyBadgerBFT" as hbbft
object "Tendermint" as tendermint
object "Polkadot" as polkadot
object "Casper FFG" as ffg
object "Casper CBC" as cbc
object "Ouroboros" as ouroboros

rampart --> pbft
securering --> pbft
pbft --> hbbft
dls --> tendermint
hbbft --> polkadot
tendermint --> polkadot
pbft --> ffg

object dls {
  set of partially synchronous algos
  ⅓ byzantine tolerance
}

object tendermint {
  partially synchronous
  ⅓ byzantine tolerance
}

object polkadot {
  (no complete consensus description)
  Validators sign blocks in Replay chain
  - selected by Nominated Proof of Stake (NPoS)
  - incentivised by (1) inflation (2) transaction fees
  - sr-NaS: prevented by long stake withholding
  - lr-NaS: prevented by hardcoding block hash snapshots in clients code
}
@enduml
